brain_two/brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

brain_two/todos/urls.py
from django.urls import path
from .views import TodoListCreateView, todo_list_detail, todo_list

app_name = "todos"

urlpatterns = [
    path("", todo_list, name="todo_lists"),
    path("<int:id>/", todo_list_detail, name="todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name="todo_list_create"),
]

brain_two/todos/models.py
from django.db import models

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        TodoList, on_delete=models.CASCADE, related_name="items"
    )

brain_two/todos/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import TodoList


# Create your views here.


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todos/todo_list_create.html"
    fields = ["name"]
    success_url = reverse_lazy("todo_list_detail")


def todo_list(request):
    todo_lists = TodoList.objects.all()
    context = {"todo_lists": todo_lists}
    return render(request, "todos/todo_list.html", context)


def todo_list_detail(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    todo_items = todo_list.items.all()
    context = {
        "todo_list": todo_list,
        "todo_items": todo_items,
    }
    return render(request, "todos/todo_list_detail.html", context)

brain_two/todos/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}
</head>
<body>
    <div id="header">
        <h1>{% block header %}{% endblock %}</h1>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="footer">
        {% block footer %}{% endblock %}
    </div>
    {% block scripts %}{% endblock %}
</body>
</html>

brain_two/todos/templates/todos/todo_list.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div>
    <h1>To-Do Lists</h1>
    <p><a href="{% url 'todos:todo_list_create' %}">Create a new list</a></p>
    <table>
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        {% for todo_list in todo_lists %}
        <tr>
          <td><a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a></td>
        </tr>
        {% empty %}
        <tr>
          <td>No to-do lists found.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock %}

brain_two/todos/templates/todos/todo_list_create.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div>
    <h1>Create a new list</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
</main>
{% endblock %}

brain_two/todos/templates/todos/todo_list_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h1>{{ todo_list.name }}</h1>
    <h2>Tasks</h2>
    <table>
      <thead>
        <tr>
          <th>Task</th>
          <th>Due Date</th>
        </tr>
      </thead>
      <tbody>
        {% for item in todo_items %}
          <tr>
            <td>{{ item.task }}</td>
            <td>{{ item.due_date }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}